name: Dog Face GIF by MOODMAN
source: >-
  https://old.reddit.com/r/reactiongifs/comments/93x8dv/mfw_i_accidentally_open_the_front_camera/
keywords:
  - funny
  - dog
  - face
  - front camera
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0
    angle: 0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.2
    stop: 0.55
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0.8
    angle: 0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.65
    stop: 1
example: []
overlay:
  - center_x: 0.25
    center_y: 0.2
    angle: 0
    scale: 0.2
