name: cute aww GIF
source: >-
  https://www.reddit.com/r/aww/comments/9p5nj9/identical_twins_discover_each_other/
keywords:
  - cute
  - adorable
  - aww
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0
    angle: 0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.2
    stop: 0.55
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0.8
    angle: 0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.65
    stop: 1
example: []
overlay:
  - center_x: 0.25
    center_y: 0.2
    angle: 0
    scale: 0.2
