services:
  memegen:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DEBUG: "false"
      SERVER_NAME: "gen.memeprof.com"
      RELEASE_STAGE: "production"
      SCHEME: "https"
      PATH: "/root/.asdf/shims:$PATH"
    volumes:
      - .:/app
    command: make run