name: Ha Ha Smile GIF by The Tonight Show Starring Jimmy Fallon
source: 'YouTube.com/FallonTonight '
keywords:
  - funny
  - smile
  - lol
  - laugh
  - reactions
  - laughing
  - nope
  - point
  - haha
  - pointing
  - laughter
  - sarcastic
  - sarcasm
  - hahaha
  - ahh
  - gotcha
  - shaq
  - finger guns
  - clever
  - tonightshow
  - ha ha
  - cracking up
  - lolol
  - divertente
  - laughing out loud
  - fingerguns
  - hehehehe
  - wkwkwk
  - i see what you did there
  - hahahahahahahahahaha
  - wkwkwkw
  - busting up
  - lol joy
  - shaquille o'neal
  - lollll
  - shaquille o neal
  - shaq laughing
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0
    angle: 0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.2
    stop: 0.55
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0.8
    angle: 0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.65
    stop: 1
example: []
overlay:
  - center_x: 0.25
    center_y: 0.2
    angle: 0
    scale: 0.2
