name: Lurk The Unknown GIF by MOODMAN
source: ''
keywords:
  - meme
  - creepy
  - mirror
  - experience
  - hiding
  - glasgow
  - unknown
  - lurking
  - wonka
  - lurk
  - the unknown
  - willy wonka experience
  - wonka experience
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0
    angle: 0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.2
    stop: 0.55
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0.8
    angle: 0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.65
    stop: 1
example: []
overlay:
  - center_x: 0.25
    center_y: 0.2
    angle: 0
    scale: 0.2
