name: Dog Aww GIF
source: >-
  https://www.reddit.com/r/Eyebleach/comments/9ix5s3/the_return_of_the_roundest_curly_floofer/
keywords:
  - cute
  - dog
  - adorable
  - aww
  - cute dog
  - eyebleach
  - floof
  - round dog
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0
    angle: 0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.2
    stop: 0.55
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0.8
    angle: 0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.65
    stop: 1
example: []
overlay:
  - center_x: 0.25
    center_y: 0.2
    angle: 0
    scale: 0.2
