name: Kirsten Dunst Lol GIF
source: >-
  http://www.reactiongifs.com/kirsten-dunst-lol/?utm_source=rss&utm_medium=rss&utm_campaign=kirsten-dunst-lol
keywords:
  - funny
  - lol
  - laugh
  - reactions
  - laughing
  - haha
  - hilarious
  - hahaha
  - funny gif
  - giggle
  - pout
  - kirsten dunst
  - divertidos
  - divertente
  - very funny
  - heheh
  - hehehehe
  - hahahah
  - thats funny
  - ‏ههه
  - ‏هـههه
  - chistosos
  - laughing gif
  - loll
  - just for laughs
  - xa-xa
  - jajajjaa
  - girl laughing
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0
    angle: 0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.2
    stop: 0.55
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0.8
    angle: 0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.65
    stop: 1
example: []
overlay:
  - center_x: 0.25
    center_y: 0.2
    angle: 0
    scale: 0.2
