name: Hungry Great British Bake Off GIF by Cartuna
source: https://story.snapchat.com/p/e0aa8121-4c39-496f-8a94-ddbef9ed2c81
keywords:
  - funny
  - animation
  - yummy
  - hungry
  - cooking
  - yum
  - baking
  - snapchat
  - rude
  - hangry
  - chew
  - great british bake off
  - bake off
  - cartuna
  - paul hollywood
  - wwdd
  - tastes great
  - don dante
  - winner winner dinner dinner
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0
    angle: 0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.2
    stop: 0.55
  - style: upper
    color: white
    font: thick
    anchor_x: 0
    anchor_y: 0.8
    angle: 0
    scale_x: 1
    scale_y: 0.2
    align: center
    start: 0.65
    stop: 1
example: []
overlay:
  - center_x: 0.25
    center_y: 0.2
    angle: 0
    scale: 0.2
